name: hotel_app_for_sobes
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-16.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Service locator
  get_it: ^7.6.6

  #work with api
  dio: ^5.4.0
  retrofit: ^4.0.3

  #check internet connection
  connectivity_plus: ^5.0.2

  #sereliazitaion, comapare objects
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  freezed: ^2.4.6

  #state management
  flutter_bloc: ^8.1.3

  #routing
  auto_route: ^7.8.4

  #UI
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  flutter_screenutil: ^5.9.0
  mask_text_input_formatter: ^2.8.0

  #localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  auto_route_generator: ^7.3.2

  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/svg/icons/
    - assets/images/
    
flutter_intl:
  enabled: true
